import { StyleSheet } from 'react-native';
import { colors, radius, spacing, fontFamilies } from '../../../../../shared/theme/tokens';

/**
 * Styles shared across onboarding step components. Values are identical to the
 * original monolithic OnboardingScreen stylesheet.
 */
export const stepStyles = StyleSheet.create({
  choicesInner: { gap: 0 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 12 },
  desc: { fontSize: 14, color: colors.textSecondary, marginBottom: 16, lineHeight: 20 },
  // FitBody lila subtitle bar → MR surfaceRaised
  fitBodySubtitleBar: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radius.lg,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  fitBodySubtitleText: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  // KG/LB — CM/FT unit toggle
  unitToggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.surfaceRaised,
    borderRadius: radius.full,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
    gap: 0,
  },
  unitToggleBtn: {
    paddingHorizontal: 28,
    paddingVertical: 8,
    borderRadius: radius.full,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitToggleBtnActive: { backgroundColor: colors.primary },
  unitToggleText: { fontSize: 14, fontWeight: '700', color: colors.textSecondary },
  unitToggleTextActive: { color: colors.base },
  unitToggleDivider: { width: 1, height: 20, backgroundColor: colors.border, marginHorizontal: 2 },
  // Weight / Age / Height display row
  weightDisplayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    marginBottom: 8,
  },
  weightArrowBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  weightArrowText: { fontSize: 22, fontWeight: '700', color: colors.text, lineHeight: 24 },
  weightValueBox: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
    minWidth: 120,
    justifyContent: 'center',
  },
  weightNumber: {
    fontFamily: fontFamilies.displayBlack,
    fontSize: 48,
    lineHeight: 48,
    color: colors.text,
    fontWeight: '900',
  },
  weightUnitLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textSecondary,
    marginBottom: 6,
  },
  // Horizontal ruler
  rulerIndicatorWrap: { alignItems: 'center', height: 12, marginBottom: 0, marginTop: 8 },
  rulerTriangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderTopWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: colors.primary,
  },
  rulerBar: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    marginTop: 6,
    overflow: 'hidden',
    position: 'relative',
  },
  rulerCenterLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: 2,
    marginLeft: -1,
    backgroundColor: colors.primary,
    opacity: 0.9,
    zIndex: 0,
  },
  rulerItem: { width: 52, alignItems: 'center', justifyContent: 'flex-start', gap: 6, zIndex: 1 },
  rulerNumber: { fontSize: 14, fontWeight: '600', textAlign: 'center' },
  rulerNumberUnselected: { color: colors.textSecondary, fontSize: 13, opacity: 0.9 },
  rulerNumberMajor: { color: colors.text, opacity: 0.7 },
  rulerNumberSelected: { color: colors.primary, fontSize: 32, fontWeight: '900', lineHeight: 32 },
  rulerTick: { borderRadius: 1, backgroundColor: colors.border },
  rulerTickMinor: { width: 1.5, height: 10, opacity: 0.6 },
  rulerTickMajor: {
    width: 1.5,
    height: 18,
    backgroundColor: colors.textSecondary,
    opacity: 0.9,
  },
  rulerTickSelected: { backgroundColor: colors.primary, width: 2, height: 22, opacity: 1 },
  rulerHint: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 10,
    opacity: 0.8,
  },
  // Choice cards — FitBody structure, MR palette
  choiceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginBottom: 10,
  },
  choiceCardActive: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}14`,
  },
  choiceContent: { flex: 1 },
  choiceLabel: { fontSize: 16, fontWeight: '700', color: colors.text },
  choiceLabelActive: { color: colors.primary },
  choiceDesc: { fontSize: 13, color: colors.textSecondary, marginTop: 2, lineHeight: 18 },
  choiceIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: `${colors.primary}14`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkCircleInactive: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: 'transparent',
  },
});
